import "./globals.css";
import { Rubik, Nunito } from "@next/font/google";

const rubik = Rubik({ subsets: ["latin"], variable: "--font-rubik" });

const nunito = Nunito({ subsets: ["latin"], variable: "--font-nunito" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} ${nunito.variable}`}>{children}</body>
    </html>
  );
}
